### ISSUE TITLE
External Reflection on Cockpit Glass - Please Remove

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/stearman#4]
The reflection of the outside terrain onto the cockpit glass windshields obscures vision thru windshield which is hazardous for landing operations. So while it was a neat idea, could you remove the FusoGlassExt graphics from the <[rigidbodygraphics][Fuselage][] Geometry list. This would be a quality of life improvement for all users and should be done for the main branch stearman.tmd file.

Here is how it looks with FusoGlassExt  in the geometry list
![20230210085125_1](https://user-images.githubusercontent.com/69315126/218150755-db15b61a-89e0-4683-8e3e-21bfbeb76825.jpg)

here is how it looks with FusoGlassExt  removed from the geometry list
 
![20230210085140_1](https://user-images.githubusercontent.com/69315126/218150725-cf9810bc-3ad1-4b00-91d0-03f4f4096c15.jpg)

**Comment by krzysk1** [comment]
fixed
