### ISSUE TITLE
Aircraft start on runway with engine not running

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/stearman#5]
If you start on the runway for takeoff, the Stearman engine stops and the engine panels open up.
Turns out the stearman_takeoff.tmd file has the wrong position for magnetos  (off) as shown
            <[input_discrete][Magnetos][]
                <[float64][Value][0.0]>
            >
This should be set so that the magnetos are on both so the engine keeps running as shown below
            <[input_discrete][Magnetos][]
                <[float64][Value][3.0]>
            >

here is the corrected file
[stearman_takeoff.zip](https://github.com/krzysk1/stearman/files/10716215/stearman_takeoff.zip)

**Comment by krzysk1** [comment]
thanks for report. fixed
