### ISSUE TITLE
Magnetos set to 'Off' in stearman_landing.tmd

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/stearman#6]
The current stearman_landing.tmd has magnetos set to the off position so your engine is not running on  final approach. Since it is impossible to start the engine manually from inside the cockpit this is very bad.
Currently
            <[input_discrete][Magnetos][]
                <[float64][Value][0.0]>
            >
Needs to be
            <[input_discrete][Magnetos][]
                <[float64][Value][3.0]>
            >

here is the corrected file
[stearman_landing.zip](https://github.com/krzysk1/stearman/files/10716237/stearman_landing.zip)

**Comment by krzysk1** [comment]
thanks for report. fixed
