### ISSUE TITLE
Cannot manually start the engine 

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/stearman#8]
Starting cold and dark or before engine start, after assigning shortcut keys for magneto switch positions and for engine starter start I still cannot manually start the stearman engine. Fuel mixture full rich, throttle idle, magneto's 1+2, engage starter shortcut key... engine turns over but does not start running. There is no assignable command for fuel cutoff valve so don't really know if fuel is getting to the engine.

**Comment by krzysk1** [comment]
Thank you for testing my aiplanes. I can't fix them at the moment as I have a lot of tasks that have come up since the New year. I hope that I will be able to deal with them soon and from March  I will be able to start making modifications

**Comment by jayeye2011** [comment]
Looking forward to you model updates. The PT-17 could definitely use a 3D panel and controls update if you can find the time. Thanks
