### ISSUE TITLE
RPMMaping Scale WRONG

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/stearman#9]
At full throttle, the engine RPM does not correctly scale on the high end. This is because the RPMMapping is wrong.
currently it scaled for a gauge that goes from  0 to 35x100 RPM
            <[graphics_linear_interpolation][RPMMapping][]
                <[string8][Input][RPMInput.Output]>
                <[tmvector2d][Map][(0.0 -2.41) (350 2.41)]>
            >
It should be
            <[graphics_linear_interpolation][RPMMapping][]
                <[string8][Input][RPMInput.Output]>
                <[tmvector2d][Map][(0.0 -2.41) (250 2.41)]>
            >
because the actual RPM gauge goes from 0 to 25x100 RPM 
[rpm gage stearman_tmd.zip](https://github.com/krzysk1/stearman/files/10718353/rpm.gage.stearman_tmd.zip)

**Comment by krzysk1** [comment]
thanks for report. Fixed
